command! -nargs=0 VGS call vim_gnome_shell#VGS()
command! -nargs=0 VGSEnable call vim_gnome_shell#VGSEnable()
command! -nargs=0 VGSDisable call vim_gnome_shell#VGSDisable()
command! -nargs=0 VGSCheck call vim_gnome_shell#VGSAuCheck()
command! -nargs=0 VGSInsertUUID call vim_gnome_shell#VGSInsert(g:vim_gnome_shell_uuid)
command! -nargs=0 VGSInsertName call vim_gnome_shell#VGSInsert(g:vim_gnome_shell_name)
command! -nargs=0 VGSAppendUUID call vim_gnome_shell#VGSAppend(g:vim_gnome_shell_uuid)
command! -nargs=0 VGSAppendName call vim_gnome_shell#VGSAppend(g:vim_gnome_shell_name)
